server:
  port: 9001

spring:
  application:
    name: Church

  datasource:
    url: jdbc:postgresql://db:5432/ChurchTest_Db
    username: postgres
    password: 0399
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: true

  sql:
    init:
      mode: always
      platform: postgres
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
