spring:
  datasource:
    url: jdbc:postgresql://db:5432/ChurchTest_Db
    username: postgres
    password: 0399
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never
      schema-locations: none
      data-locations: none

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
